version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: fileshare
      POSTGRES_USER: fs_user
      POSTGRES_PASSWORD: fs_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: ["5432:5432"]

  backend:
    build:
      context: .
    container_name: fs-backend
    image: fs-backend:latest
    env_file: .env.docker
    depends_on: [db]
    ports: ["8000:8000"]

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    container_name: fs-scheduler
    image: fs-scheduler:latest
    env_file: .env.docker
    depends_on: [db]

volumes:
  pgdata:
