"""create core tables

Revision ID: dc7ae4b008f5
Revises: 
Create Date: 2025-10-06 12:08:28.485586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7ae4b008f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_code', sa.String(length=16), nullable=False),
    sa.Column('location_code', sa.String(length=32), nullable=False),
    sa.Column('share_unc', sa.String(length=512), nullable=False),
    sa.Column('paths_json', sa.JSON(), nullable=False),
    sa.Column('scheduled_est', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result_message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_requests_location_code'), 'archive_requests', ['location_code'], unique=False)
    op.create_index(op.f('ix_archive_requests_region_code'), 'archive_requests', ['region_code'], unique=False)
    op.create_index(op.f('ix_archive_requests_scheduled_est'), 'archive_requests', ['scheduled_est'], unique=False)
    op.create_index(op.f('ix_archive_requests_share_unc'), 'archive_requests', ['share_unc'], unique=False)
    op.create_index(op.f('ix_archive_requests_status'), 'archive_requests', ['status'], unique=False)
    op.create_table('regions',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('region_code', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['region_code'], ['regions.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_code'), 'locations', ['code'], unique=True)
    op.create_index(op.f('ix_locations_region_code'), 'locations', ['region_code'], unique=False)
    op.create_table('shares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unc_path', sa.String(length=512), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shares_location_id'), 'shares', ['location_id'], unique=False)
    op.create_index(op.f('ix_shares_unc_path'), 'shares', ['unc_path'], unique=True)
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('is_dir', sa.Boolean(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['share_id'], ['shares.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_modified_at'), 'nodes', ['modified_at'], unique=False)
    op.create_index(op.f('ix_nodes_name'), 'nodes', ['name'], unique=False)
    op.create_index(op.f('ix_nodes_path'), 'nodes', ['path'], unique=False)
    op.create_index(op.f('ix_nodes_share_id'), 'nodes', ['share_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodes_share_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_path'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_name'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_modified_at'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_shares_unc_path'), table_name='shares')
    op.drop_index(op.f('ix_shares_location_id'), table_name='shares')
    op.drop_table('shares')
    op.drop_index(op.f('ix_locations_region_code'), table_name='locations')
    op.drop_index(op.f('ix_locations_code'), table_name='locations')
    op.drop_table('locations')
    op.drop_table('regions')
    op.drop_index(op.f('ix_archive_requests_status'), table_name='archive_requests')
    op.drop_index(op.f('ix_archive_requests_share_unc'), table_name='archive_requests')
    op.drop_index(op.f('ix_archive_requests_scheduled_est'), table_name='archive_requests')
    op.drop_index(op.f('ix_archive_requests_region_code'), table_name='archive_requests')
    op.drop_index(op.f('ix_archive_requests_location_code'), table_name='archive_requests')
    op.drop_table('archive_requests')
    # ### end Alembic commands ###
